In [3]:
import numpy as np

print(np.__version__)

1.26.4


In [3]:
arr=np.array([1,2,3,4,5])
arr=arr*2
print(arr)


[ 2  4  6  8 10]


In [ ]:
#multidimensional array
import numpy as np
arr1=np.array('A')
print(arr1.ndim)
arr2=np.array(['1,2,4'])
print(arr2.ndim)
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3.ndim)
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr4.ndim)
arr5=np.array([
    [
        [['a','b','c'],
         ['d','e','f']],

        [['g','h','i'],
         ['j','k','l']]
    ],
    [
        [['m','n','o'],
         ['p','q','r']],

        [['s','t','u'],
         ['v','w','x']]
    ]
            ])
print(arr5.ndim)
print(arr5.shape)

0
1
2
3
4
(2, 2, 2, 3)


In [19]:
arr5=np.array([
    [
        [['a','b','c'],
         ['d','e','f']],

        [['g','h','i'],
         ['j','k','l']]
    ],
    [
        [['m','n','o'],
         ['p','q','r']],

        [['s','t','u'],
         ['v','w','x']]
    ]
            ])

print(arr5[0,0,1,0])
word=arr5[0,0,0,0]+ arr5[1,0,1,0] +arr5[1,0,1,0]+arr5[0,1,1,2]+arr5[0,0,1,1]
print(word)

d
apple


In [84]:
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
print(array)

#slicing
print(array[:,0:1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1]
 [ 5]
 [ 9]
 [13]]


In [97]:
#arithmetic
arr=np.array([[1,2,3],[4,5,6]])

print(arr+arr)
print()
print(arr-arr)
print()
print(arr*2)
print()
print(arr/2)
print()
print(arr//2)
print()
print(arr%2)
print()
print(arr**2)
print()
print(sum(arr))
print()
print(sum(sum(arr)))

[[ 2  4  6]
 [ 8 10 12]]

[[0 0 0]
 [0 0 0]]

[[ 2  4  6]
 [ 8 10 12]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]]

[[0 1 1]
 [2 2 3]]

[[1 0 1]
 [0 1 0]]

[[ 1  4  9]
 [16 25 36]]

[5 7 9]

21


In [118]:
#vectorized math functions
arr=np.array([[1,2.7,3.5],[4,5,6]])

print(np.sqrt(arr))
print(np.round(arr))
print(np.ceil(arr))
print(np.floor(arr))
print(np.abs(arr))
print(np.pi)
print(np.exp(arr))
print(np.log(arr))
print(np.log10(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[[1.         1.64316767 1.87082869]
 [2.         2.23606798 2.44948974]]
[[1. 3. 4.]
 [4. 5. 6.]]
[[1. 3. 4.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.  2.7 3.5]
 [4.  5.  6. ]]
3.141592653589793
[[  2.71828183  14.87973172  33.11545196]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.99325177 1.25276297]
 [1.38629436 1.60943791 1.79175947]]
[[0.         0.43136376 0.54406804]
 [0.60205999 0.69897    0.77815125]]
[[ 0.84147098  0.42737988 -0.35078323]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.90407214 -0.93645669]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -0.47272763  0.37458564]
 [ 1.15782128 -3.38051501 -0.29100619]]


In [ ]:
#task

radii=np.array([1,2,3])

area=np.pi*(radii**2)
print(area)




[ 3.14159265 12.56637061 28.27433388]


In [124]:
#elementwise arthimetic

arr=np.array([1,2,3])
arr1=np.array([4,5,6])

print(arr+arr1)
print(arr-arr1)
print(arr*arr1)
print(arr/arr1)
print(arr//arr1)
print(arr%arr1)
print(arr**arr1)




[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]


In [129]:
#comparison operators

scores=np.array([90,80,70,60,50])
print(scores>70)
print(scores>=70)
print(scores[scores<90])

scores[scores<70]=0
print(scores)

[ True  True False False False]
[ True  True  True False False]
[80 70 60 50]
[90 80 70  0  0]


In [135]:
#brocasting allows numpy to perform operations on arrays
# with different shapes. by virtually expanding the dimensions
# so they match the larger array's shape

#the dimensions have the same size or one of them is 1 


arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1],[2],[3]])

print(arr1.shape)
print(arr2.shape)

print(arr1*arr2)
arr3=arr1*arr2
print(arr3.shape)



(3, 3)
(3, 1)
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
(3, 3)


In [144]:
#aggregate functions
#summerize data and typically returns a single value

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmin(arr))

45
[12 15 18]
9
1
5.0
5.0
2.581988897471611
6.666666666666667
0


In [14]:
#filtering 
#refers to the process of selecting specific elements from an array based on certain conditions.
import numpy as np

ages=np.array([[11,23,32],[12,21,23]])

teenages=ages[ages<20]
adults=ages[(ages>=20) &(ages<30)]

evens=ages[ages%2==0]
mul=ages[ages*2>60]
print(teenages,adults,evens,mul)
np.where(ages>20,ages,0)



[11 12] [23 21 23] [32 12] [32]


array([[ 0, 23, 32],
       [ 0, 21, 23]])

In [141]:
rng=np.random.default_rng()

print(rng.integers(low=1,high=101,size=(3,4)))

print(np.random.uniform(low=-1,high=1,size=(3,4)))

rng=np.random.default_rng()

arr=np.array([1,2,3,4,5,6,7])
rng.shuffle(arr)
print(arr)

fruits=np.array(['apple','banana','cherry','date','elderberry'])
fruit=rng.choice(fruits,size=3)
print(fruit)


[[95 89 53 68]
 [77 66 57 16]
 [67 12 50 98]]
[[ 0.4761847  -0.14142372  0.30709895 -0.94870352]
 [-0.86550906  0.70318393 -0.31276409  0.3598793 ]
 [ 0.62160205  0.15264668 -0.24555747 -0.80945542]]
[7 6 5 2 1 4 3]
['apple' 'elderberry' 'apple']
